---
title: "DB1C"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
if (! 'devtools' %in% installed.packages()[,1]){
  install.packages("devtools")
}

if (! 'fontawesome' %in% installed.packages()[,1]){
  devtools::install_github("rstudio/fontawesome")
}

available_packages <- installed.packages()[,1]  # what's available ?

if (! 'pacman' %in% available_packages){
  install.packages("pacman")        # install if needed
}

pacman::p_load(tidyverse)   # meta-package
pacman::p_load(glue)
pacman::p_load(stringr)
pacman::p_load(ggmosaic)
pacman::p_load(ggforce)
pacman::p_load(patchwork)
pacman::p_load(summarytools)
pacman::p_load(skimr)
pacman::p_load(GGally)
pacman::p_load(arrow)
pacman::p_load(here)
pacman::p_load(fs)

rm(available_packages)      # Ockham's razor

old_theme <- theme_set(theme_minimal(base_family = "Helvetica Neue"))
```

```{r}
library(arrow)
library(dplyr)
library(here)

df_market_202602 <- read_parquet(
  '/Users/alexandre/Documents/stage_2026_UdeM/data/raw/DB1C/DB1C.MARKET.202507.22MAY2026.parquet'
)

glimpse(df_market_202602)
```

```{r}
ggplot(df_market_202602, aes(x = PurchaseWindowGroup)) +
  geom_bar(fill = 'purple', color = 'black') +
  labs(
    title = "Nombre de tickets par fenêtre d'achat",
    x = "Fenêtre d'achat",
    y = "Nombre de tickets"
  ) +
  theme_classic()
```

```{r}
library(here); library(arrow); library(dplyr); library(ggplot2); library(fs)
source(here("R", "import.R"))
source(here("R", "features.R"))

lookups <- load_lookups()
```

```{r}
df_market_202602 %>% filter(V_Yield == 1) %>% count(ItinID)
```

```{r}

```


